<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id()->primary();
            $table->char('countrycode', 3);
            $table->string('countryname', 200);
            $table->char('code', 2)->nullable();
        });

        // Insert data
        DB::table('countries')->insert([
            ['countrycode' => 'AFG', 'countryname' => 'Afghanistan', 'code' => 'AF'],
            ['countrycode' => 'ALA', 'countryname' => 'Åland', 'code' => 'AX'],
            ['countrycode' => 'ALB', 'countryname' => 'Albania', 'code' => 'AL'],
            ['countrycode' => 'DZA', 'countryname' => 'Algeria', 'code' => 'DZ'],
            ['countrycode' => 'ASM', 'countryname' => 'American Samoa', 'code' => 'AS'],
            ['countrycode' => 'AND', 'countryname' => 'Andorra', 'code' => 'AD'],
            ['countrycode' => 'AGO', 'countryname' => 'Angola', 'code' => 'AO'],
            ['countrycode' => 'AIA', 'countryname' => 'Anguilla', 'code' => 'AI'],
            ['countrycode' => 'ATA', 'countryname' => 'Antarctica', 'code' => 'AQ'],
            ['countrycode' => 'ATG', 'countryname' => 'Antigua and Barbuda', 'code' => 'AG'],
            ['countrycode' => 'ARG', 'countryname' => 'Argentina', 'code' => 'AR'],
            ['countrycode' => 'ARM', 'countryname' => 'Armenia', 'code' => 'AM'],
            ['countrycode' => 'ABW', 'countryname' => 'Aruba', 'code' => 'AW'],
            ['countrycode' => 'AUS', 'countryname' => 'Australia', 'code' => 'AU'],
            ['countrycode' => 'AUT', 'countryname' => 'Austria', 'code' => 'AT'],
            ['countrycode' => 'AZE', 'countryname' => 'Azerbaijan', 'code' => 'AZ'],
            ['countrycode' => 'BHS', 'countryname' => 'Bahamas', 'code' => 'BS'],
            ['countrycode' => 'BHR', 'countryname' => 'Bahrain', 'code' => 'BH'],
            ['countrycode' => 'BGD', 'countryname' => 'Bangladesh', 'code' => 'BD'],
            ['countrycode' => 'BRB', 'countryname' => 'Barbados', 'code' => 'BB'],
            ['countrycode' => 'BLR', 'countryname' => 'Belarus', 'code' => 'BY'],
            ['countrycode' => 'BEL', 'countryname' => 'Belgium', 'code' => 'BE'],
            ['countrycode' => 'BLZ', 'countryname' => 'Belize', 'code' => 'BZ'],
            ['countrycode' => 'BEN', 'countryname' => 'Benin', 'code' => 'BJ'],
            ['countrycode' => 'BMU', 'countryname' => 'Bermuda', 'code' => 'BM'],
            ['countrycode' => 'BTN', 'countryname' => 'Bhutan', 'code' => 'BT'],
            ['countrycode' => 'BOL', 'countryname' => 'Bolivia', 'code' => 'BO'],
            ['countrycode' => 'BES', 'countryname' => 'Bonaire', 'code' => 'BQ'],
            ['countrycode' => 'BIH', 'countryname' => 'Bosnia and Herzegovina', 'code' => 'BA'],
            ['countrycode' => 'BWA', 'countryname' => 'Botswana', 'code' => 'BW'],
            ['countrycode' => 'BVT', 'countryname' => 'Bouvet Island', 'code' => 'BV'],
            ['countrycode' => 'BRA', 'countryname' => 'Brazil', 'code' => 'BR'],
            ['countrycode' => 'IOT', 'countryname' => 'British Indian Ocean Territory', 'code' => 'IO'],
            ['countrycode' => 'VGB', 'countryname' => 'British Virgin Islands', 'code' => 'VG'],
            ['countrycode' => 'BRN', 'countryname' => 'Brunei', 'code' => 'BN'],
            ['countrycode' => 'BGR', 'countryname' => 'Bulgaria', 'code' => 'BG'],
            ['countrycode' => 'BFA', 'countryname' => 'Burkina Faso', 'code' => 'BF'],
            ['countrycode' => 'BDI', 'countryname' => 'Burundi', 'code' => 'BI'],
            ['countrycode' => 'KHM', 'countryname' => 'Cambodia', 'code' => 'KH'],
            ['countrycode' => 'CMR', 'countryname' => 'Cameroon', 'code' => 'CM'],
            ['countrycode' => 'CAN', 'countryname' => 'Canada', 'code' => 'CA'],
            ['countrycode' => 'CPV', 'countryname' => 'Cape Verde', 'code' => 'CV'],
            ['countrycode' => 'CYM', 'countryname' => 'Cayman Islands', 'code' => 'KY'],
            ['countrycode' => 'CAF', 'countryname' => 'Central African Republic', 'code' => 'CF'],
            ['countrycode' => 'TCD', 'countryname' => 'Chad', 'code' => 'TD'],
            ['countrycode' => 'CHL', 'countryname' => 'Chile', 'code' => 'CL'],
            ['countrycode' => 'CHN', 'countryname' => 'China', 'code' => 'CN'],
            ['countrycode' => 'CXR', 'countryname' => 'Christmas Island', 'code' => 'CX'],
            ['countrycode' => 'CCK', 'countryname' => 'Cocos [Keeling] Islands', 'code' => 'CC'],
            ['countrycode' => 'COL', 'countryname' => 'Colombia', 'code' => 'CO'],
            ['countrycode' => 'COM', 'countryname' => 'Comoros', 'code' => 'KM'],
            ['countrycode' => 'COK', 'countryname' => 'Cook Islands', 'code' => 'CK'],
            ['countrycode' => 'CRI', 'countryname' => 'Costa Rica', 'code' => 'CR'],
            ['countrycode' => 'HRV', 'countryname' => 'Croatia', 'code' => 'HR'],
            ['countrycode' => 'CUB', 'countryname' => 'Cuba', 'code' => 'CU'],
            ['countrycode' => 'CUW', 'countryname' => 'Curacao', 'code' => 'CW'],
            ['countrycode' => 'CYP', 'countryname' => 'Cyprus', 'code' => 'CY'],
            ['countrycode' => 'CZE', 'countryname' => 'Czech Republic', 'code' => 'CZ'],
            ['countrycode' => 'COD', 'countryname' => 'Democratic Republic of the Congo', 'code' => 'CD'],
            ['countrycode' => 'DNK', 'countryname' => 'Denmark', 'code' => 'DK'],
            ['countrycode' => 'DJI', 'countryname' => 'Djibouti', 'code' => 'DJ'],
            ['countrycode' => 'DMA', 'countryname' => 'Dominica', 'code' => 'DM'],
            ['countrycode' => 'DOM', 'countryname' => 'Dominican Republic', 'code' => 'DO'],
            ['countrycode' => 'TLS', 'countryname' => 'East Timor', 'code' => 'TL'],
            ['countrycode' => 'ECU', 'countryname' => 'Ecuador', 'code' => 'EC'],
            ['countrycode' => 'EGY', 'countryname' => 'Egypt', 'code' => 'EG'],
            ['countrycode' => 'SLV', 'countryname' => 'El Salvador', 'code' => 'SV'],
            ['countrycode' => 'GNQ', 'countryname' => 'Equatorial Guinea', 'code' => 'GQ'],
            ['countrycode' => 'ERI', 'countryname' => 'Eritrea', 'code' => 'ER'],
            ['countrycode' => 'EST', 'countryname' => 'Estonia', 'code' => 'EE'],
            ['countrycode' => 'SWZ', 'countryname' => 'Eswatini', 'code' => 'SZ'],
            ['countrycode' => 'ETH', 'countryname' => 'Ethiopia', 'code' => 'ET'],
            ['countrycode' => 'FLK', 'countryname' => 'Falkland Islands', 'code' => 'FK'],
            ['countrycode' => 'FRO', 'countryname' => 'Faroe Islands', 'code' => 'FO'],
            ['countrycode' => 'FJI', 'countryname' => 'Fiji', 'code' => 'FJ'],
            ['countrycode' => 'FIN', 'countryname' => 'Finland', 'code' => 'FI'],
            ['countrycode' => 'FRA', 'countryname' => 'France', 'code' => 'FR'],
            ['countrycode' => 'GUF', 'countryname' => 'French Guiana', 'code' => 'GF'],
            ['countrycode' => 'PYF', 'countryname' => 'French Polynesia', 'code' => 'PF'],
            ['countrycode' => 'ATF', 'countryname' => 'French Southern Territories', 'code' => 'TF'],
            ['countrycode' => 'GAB', 'countryname' => 'Gabon', 'code' => 'GA'],
            ['countrycode' => 'GMB', 'countryname' => 'Gambia', 'code' => 'GM'],
            ['countrycode' => 'GEO', 'countryname' => 'Georgia', 'code' => 'GE'],
            ['countrycode' => 'DEU', 'countryname' => 'Germany', 'code' => 'DE'],
            ['countrycode' => 'GHA', 'countryname' => 'Ghana', 'code' => 'GH'],
            ['countrycode' => 'GIB', 'countryname' => 'Gibraltar', 'code' => 'GI'],
            ['countrycode' => 'GRC', 'countryname' => 'Greece', 'code' => 'GR'],
            ['countrycode' => 'GRL', 'countryname' => 'Greenland', 'code' => 'GL'],
            ['countrycode' => 'GRD', 'countryname' => 'Grenada', 'code' => 'GD'],
            ['countrycode' => 'GLP', 'countryname' => 'Guadeloupe', 'code' => 'GP'],
            ['countrycode' => 'GUM', 'countryname' => 'Guam', 'code' => 'GU'],
            ['countrycode' => 'GTM', 'countryname' => 'Guatemala', 'code' => 'GT'],
            ['countrycode' => 'GGY', 'countryname' => 'Guernsey', 'code' => 'GG'],
            ['countrycode' => 'GIN', 'countryname' => 'Guinea', 'code' => 'GN'],
            ['countrycode' => 'GNB', 'countryname' => 'Guinea-Bissau', 'code' => 'GW'],
            ['countrycode' => 'GUY', 'countryname' => 'Guyana', 'code' => 'GY'],
            ['countrycode' => 'HTI', 'countryname' => 'Haiti', 'code' => 'HT'],
            ['countrycode' => 'HMD', 'countryname' => 'Heard Island and McDonald Islands', 'code' => 'HM'],
            ['countrycode' => 'HND', 'countryname' => 'Honduras', 'code' => 'HN'],
            ['countrycode' => 'HKG', 'countryname' => 'Hong Kong', 'code' => 'HK'],
            ['countrycode' => 'HUN', 'countryname' => 'Hungary', 'code' => 'HU'],
            ['countrycode' => 'ISL', 'countryname' => 'Iceland', 'code' => 'IS'],
            ['countrycode' => 'IND', 'countryname' => 'India', 'code' => 'IN'],
            ['countrycode' => 'IDN', 'countryname' => 'Indonesia', 'code' => 'ID'],
            ['countrycode' => 'IRN', 'countryname' => 'Iran', 'code' => 'IR'],
            ['countrycode' => 'IRQ', 'countryname' => 'Iraq', 'code' => 'IQ'],
            ['countrycode' => 'IRL', 'countryname' => 'Ireland', 'code' => 'IE'],
            ['countrycode' => 'IMN', 'countryname' => 'Isle of Man', 'code' => 'IM'],
            ['countrycode' => 'ISR', 'countryname' => 'Israel', 'code' => 'IL'],
            ['countrycode' => 'ITA', 'countryname' => 'Italy', 'code' => 'IT'],
            ['countrycode' => 'CIV', 'countryname' => 'Ivory Coast', 'code' => 'CI'],
            ['countrycode' => 'JAM', 'countryname' => 'Jamaica', 'code' => 'JM'],
            ['countrycode' => 'JPN', 'countryname' => 'Japan', 'code' => 'JP'],
            ['countrycode' => 'JEY', 'countryname' => 'Jersey', 'code' => 'JE'],
            ['countrycode' => 'JOR', 'countryname' => 'Jordan', 'code' => 'JO'],
            ['countrycode' => 'KAZ', 'countryname' => 'Kazakhstan', 'code' => 'KZ'],
            ['countrycode' => 'KEN', 'countryname' => 'Kenya', 'code' => 'KE'],
            ['countrycode' => 'KIR', 'countryname' => 'Kiribati', 'code' => 'KI'],
            ['countrycode' => 'XKX', 'countryname' => 'Kosovo', 'code' => 'XK'],
            ['countrycode' => 'KWT', 'countryname' => 'Kuwait', 'code' => 'KW'],
            ['countrycode' => 'KGZ', 'countryname' => 'Kyrgyzstan', 'code' => 'KG'],
            ['countrycode' => 'LAO', 'countryname' => 'Laos', 'code' => 'LA'],
            ['countrycode' => 'LVA', 'countryname' => 'Latvia', 'code' => 'LV'],
            ['countrycode' => 'LBN', 'countryname' => 'Lebanon', 'code' => 'LB'],
            ['countrycode' => 'LSO', 'countryname' => 'Lesotho', 'code' => 'LS'],
            ['countrycode' => 'LBR', 'countryname' => 'Liberia', 'code' => 'LR'],
            ['countrycode' => 'LBY', 'countryname' => 'Libya', 'code' => 'LY'],
            ['countrycode' => 'LIE', 'countryname' => 'Liechtenstein', 'code' => 'LI'],
            ['countrycode' => 'LTU', 'countryname' => 'Lithuania', 'code' => 'LT'],
            ['countrycode' => 'LUX', 'countryname' => 'Luxembourg', 'code' => 'LU'],
            ['countrycode' => 'MAC', 'countryname' => 'Macao', 'code' => 'MO'],
            ['countrycode' => 'MKD', 'countryname' => 'Macedonia', 'code' => 'MK'],
            ['countrycode' => 'MDG', 'countryname' => 'Madagascar', 'code' => 'MG'],
            ['countrycode' => 'MWI', 'countryname' => 'Malawi', 'code' => 'MW'],
            ['countrycode' => 'MYS', 'countryname' => 'Malaysia', 'code' => 'MY'],
            ['countrycode' => 'MDV', 'countryname' => 'Maldives', 'code' => 'MV'],
            ['countrycode' => 'MLI', 'countryname' => 'Mali', 'code' => 'ML'],
            ['countrycode' => 'MLT', 'countryname' => 'Malta', 'code' => 'MT'],
            ['countrycode' => 'MHL', 'countryname' => 'Marshall Islands', 'code' => 'MH'],
            ['countrycode' => 'MTQ', 'countryname' => 'Martinique', 'code' => 'MQ'],
            ['countrycode' => 'MRT', 'countryname' => 'Mauritania', 'code' => 'MR'],
            ['countrycode' => 'MUS', 'countryname' => 'Mauritius', 'code' => 'MU'],
            ['countrycode' => 'MYT', 'countryname' => 'Mayotte', 'code' => 'YT'],
            ['countrycode' => 'MEX', 'countryname' => 'Mexico', 'code' => 'MX'],
            ['countrycode' => 'FSM', 'countryname' => 'Micronesia', 'code' => 'FM'],
            ['countrycode' => 'MDA', 'countryname' => 'Moldova', 'code' => 'MD'],
            ['countrycode' => 'MCO', 'countryname' => 'Monaco', 'code' => 'MC'],
            ['countrycode' => 'MNG', 'countryname' => 'Mongolia', 'code' => 'MN'],
            ['countrycode' => 'MNE', 'countryname' => 'Montenegro', 'code' => 'ME'],
            ['countrycode' => 'MSR', 'countryname' => 'Montserrat', 'code' => 'MS'],
            ['countrycode' => 'MAR', 'countryname' => 'Morocco', 'code' => 'MA'],
            ['countrycode' => 'MOZ', 'countryname' => 'Mozambique', 'code' => 'MZ'],
            ['countrycode' => 'MMR', 'countryname' => 'Myanmar', 'code' => 'MM'],
            ['countrycode' => 'NAM', 'countryname' => 'Namibia', 'code' => 'NA'],
            ['countrycode' => 'NRU', 'countryname' => 'Nauru', 'code' => 'NR'],
            ['countrycode' => 'NPL', 'countryname' => 'Nepal', 'code' => 'NP'],
            ['countrycode' => 'NLD', 'countryname' => 'Netherlands', 'code' => 'NL'],
            ['countrycode' => 'ANT', 'countryname' => 'Netherlands Antilles', 'code' => 'AN'],
            ['countrycode' => 'NCL', 'countryname' => 'New Caledonia', 'code' => 'NC'],
            ['countrycode' => 'NZL', 'countryname' => 'New Zealand', 'code' => 'NZ'],
            ['countrycode' => 'NIC', 'countryname' => 'Nicaragua', 'code' => 'NI'],
            ['countrycode' => 'NER', 'countryname' => 'Niger', 'code' => 'NE'],
            ['countrycode' => 'NGA', 'countryname' => 'Nigeria', 'code' => 'NG'],
            ['countrycode' => 'NIU', 'countryname' => 'Niue', 'code' => 'NU'],
            ['countrycode' => 'NFK', 'countryname' => 'Norfolk Island', 'code' => 'NF'],
            ['countrycode' => 'PRK', 'countryname' => 'North Korea', 'code' => 'KP'],
            ['countrycode' => 'MNP', 'countryname' => 'Northern Mariana Islands', 'code' => 'MP'],
            ['countrycode' => 'NOR', 'countryname' => 'Norway', 'code' => 'NO'],
            ['countrycode' => 'OMN', 'countryname' => 'Oman', 'code' => 'OM'],
            ['countrycode' => 'PAK', 'countryname' => 'Pakistan', 'code' => 'PK'],
            ['countrycode' => 'PLW', 'countryname' => 'Palau', 'code' => 'PW'],
            ['countrycode' => 'PSE', 'countryname' => 'Palestinian Territory', 'code' => 'PS'],
            ['countrycode' => 'PAN', 'countryname' => 'Panama', 'code' => 'PA'],
            ['countrycode' => 'PNG', 'countryname' => 'Papua New Guinea', 'code' => 'PG'],
            ['countrycode' => 'PRY', 'countryname' => 'Paraguay', 'code' => 'PY'],
            ['countrycode' => 'PER', 'countryname' => 'Peru', 'code' => 'PE'],
            ['countrycode' => 'PHL', 'countryname' => 'Philippines', 'code' => 'PH'],
            ['countrycode' => 'PCN', 'countryname' => 'Pitcairn', 'code' => 'PN'],
            ['countrycode' => 'POL', 'countryname' => 'Poland', 'code' => 'PL'],
            ['countrycode' => 'PRT', 'countryname' => 'Portugal', 'code' => 'PT'],
            ['countrycode' => 'PRI', 'countryname' => 'Puerto Rico', 'code' => 'PR'],
            ['countrycode' => 'QAT', 'countryname' => 'Qatar', 'code' => 'QA'],
            ['countrycode' => 'REU', 'countryname' => 'Reunion', 'code' => 'RE'],
            ['countrycode' => 'ROU', 'countryname' => 'Romania', 'code' => 'RO'],
            ['countrycode' => 'RUS', 'countryname' => 'Russia', 'code' => 'RU'],
            ['countrycode' => 'RWA', 'countryname' => 'Rwanda', 'code' => 'RW'],
            ['countrycode' => 'SHN', 'countryname' => 'Saint Helena', 'code' => 'SH'],
            ['countrycode' => 'KNA', 'countryname' => 'Saint Kitts and Nevis', 'code' => 'KN'],
            ['countrycode' => 'LCA', 'countryname' => 'Saint Lucia', 'code' => 'LC'],
            ['countrycode' => 'SPM', 'countryname' => 'Saint Pierre and Miquelon', 'code' => 'PM'],
            ['countrycode' => 'VCT', 'countryname' => 'Saint Vincent and the Grenadines', 'code' => 'VC'],
            ['countrycode' => 'WSM', 'countryname' => 'Samoa', 'code' => 'WS'],
            ['countrycode' => 'SMR', 'countryname' => 'San Marino', 'code' => 'SM'],
            ['countrycode' => 'STP', 'countryname' => 'Sao Tome and Principe', 'code' => 'ST'],
            ['countrycode' => 'SAU', 'countryname' => 'Saudi Arabia', 'code' => 'SA'],
            ['countrycode' => 'SEN', 'countryname' => 'Senegal', 'code' => 'SN'],
            ['countrycode' => 'SRB', 'countryname' => 'Serbia', 'code' => 'RS'],
            ['countrycode' => 'SYC', 'countryname' => 'Seychelles', 'code' => 'SC'],
            ['countrycode' => 'SLE', 'countryname' => 'Sierra Leone', 'code' => 'SL'],
            ['countrycode' => 'SGP', 'countryname' => 'Singapore', 'code' => 'SG'],
            ['countrycode' => 'SVK', 'countryname' => 'Slovakia', 'code' => 'SK'],
            ['countrycode' => 'SVN', 'countryname' => 'Slovenia', 'code' => 'SI'],
            ['countrycode' => 'SLB', 'countryname' => 'Solomon Islands', 'code' => 'SB'],
            ['countrycode' => 'SOM', 'countryname' => 'Somalia', 'code' => 'SO'],
            ['countrycode' => 'ZAF', 'countryname' => 'South Africa', 'code' => 'ZA'],
            ['countrycode' => 'SGS', 'countryname' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS'],
            ['countrycode' => 'KOR', 'countryname' => 'South Korea', 'code' => 'KR'],
            ['countrycode' => 'SSD', 'countryname' => 'South Sudan', 'code' => 'SS'],
            ['countrycode' => 'ESP', 'countryname' => 'Spain', 'code' => 'ES'],
            ['countrycode' => 'LKA', 'countryname' => 'Sri Lanka', 'code' => 'LK'],
            ['countrycode' => 'SDN', 'countryname' => 'Sudan', 'code' => 'SD'],
            ['countrycode' => 'SUR', 'countryname' => 'Suriname', 'code' => 'SR'],
            ['countrycode' => 'SJM', 'countryname' => 'Svalbard and Jan Mayen', 'code' => 'SJ'],
            ['countrycode' => 'SWZ', 'countryname' => 'Swaziland', 'code' => 'SZ'],
            ['countrycode' => 'SWE', 'countryname' => 'Sweden', 'code' => 'SE'],
            ['countrycode' => 'CHE', 'countryname' => 'Switzerland', 'code' => 'CH'],
            ['countrycode' => 'SYR', 'countryname' => 'Syria', 'code' => 'SY'],
            ['countrycode' => 'TWN', 'countryname' => 'Taiwan', 'code' => 'TW'],
            ['countrycode' => 'TJK', 'countryname' => 'Tajikistan', 'code' => 'TJ'],
            ['countrycode' => 'TZA', 'countryname' => 'Tanzania', 'code' => 'TZ'],
            ['countrycode' => 'THA', 'countryname' => 'Thailand', 'code' => 'TH'],
            ['countrycode' => 'TLS', 'countryname' => 'Timor-Leste', 'code' => 'TL'],
            ['countrycode' => 'TGO', 'countryname' => 'Togo', 'code' => 'TG'],
            ['countrycode' => 'TKL', 'countryname' => 'Tokelau', 'code' => 'TK'],
            ['countrycode' => 'TON', 'countryname' => 'Tonga', 'code' => 'TO'],
            ['countrycode' => 'TTO', 'countryname' => 'Trinidad and Tobago', 'code' => 'TT'],
            ['countrycode' => 'TUN', 'countryname' => 'Tunisia', 'code' => 'TN'],
            ['countrycode' => 'TUR', 'countryname' => 'Turkey', 'code' => 'TR'],
            ['countrycode' => 'TKM', 'countryname' => 'Turkmenistan', 'code' => 'TM'],
            ['countrycode' => 'TCA', 'countryname' => 'Turks and Caicos Islands', 'code' => 'TC'],
            ['countrycode' => 'TUV', 'countryname' => 'Tuvalu', 'code' => 'TV'],
            ['countrycode' => 'UGA', 'countryname' => 'Uganda', 'code' => 'UG'],
            ['countrycode' => 'UKR', 'countryname' => 'Ukraine', 'code' => 'UA'],
            ['countrycode' => 'ARE', 'countryname' => 'United Arab Emirates', 'code' => 'AE'],
            ['countrycode' => 'GBR', 'countryname' => 'United Kingdom', 'code' => 'GB'],
            ['countrycode' => 'USA', 'countryname' => 'United States', 'code' => 'US'],
            ['countrycode' => 'UMI', 'countryname' => 'United States Minor Outlying Islands', 'code' => 'UM'],
            ['countrycode' => 'URY', 'countryname' => 'Uruguay', 'code' => 'UY'],
            ['countrycode' => 'UZB', 'countryname' => 'Uzbekistan', 'code' => 'UZ'],
            ['countrycode' => 'VUT', 'countryname' => 'Vanuatu', 'code' => 'VU'],
            ['countrycode' => 'VAT', 'countryname' => 'Vatican', 'code' => 'VA'],
            ['countrycode' => 'VEN', 'countryname' => 'Venezuela', 'code' => 'VE'],
            ['countrycode' => 'VNM', 'countryname' => 'Vietnam', 'code' => 'VN'],
            ['countrycode' => 'VGB', 'countryname' => 'Virgin Islands (British)', 'code' => 'VG'],
            ['countrycode' => 'VIR', 'countryname' => 'Virgin Islands (U.S.)', 'code' => 'VI'],
            ['countrycode' => 'WLF', 'countryname' => 'Wallis and Futuna', 'code' => 'WF'],
            ['countrycode' => 'ESH', 'countryname' => 'Western Sahara', 'code' => 'EH'],
            ['countrycode' => 'YEM', 'countryname' => 'Yemen', 'code' => 'YE'],
            ['countrycode' => 'ZMB', 'countryname' => 'Zambia', 'code' => 'ZM'],
            ['countrycode' => 'ZWE', 'countryname' => 'Zimbabwe', 'code' => 'ZW'],
        ]);

    }
    public function down(): void
    {
        Schema::dropIfExists('countries');
    }
};    
